services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: homeinventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always