services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: homeinventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

    # Run 'docker-compose -f docker-compose.dev.yml up -d' to get the DB Docker Container up und running